apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendations-config
  namespace: team-recommendations
data:
  ENDPOINT_NAME: "george-recommendations-endpoint"
  AWS_REGION: "us-east-1"
  LOG_LEVEL: "info"
